# Generated by Django 2.1.7 on 2019-05-07 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Con',
            fields=[
                ('CON_ID', models.AutoField(primary_key=True, serialize=False)),
                ('CON_NAME', models.CharField(max_length=200)),
                ('CON_TAGLINE', models.CharField(max_length=500)),
                ('P_GROUP_ID', models.CharField(max_length=10000)),
                ('CON_BEGIN', models.DateTimeField()),
                ('CON_END', models.DateTimeField(null=True)),
                ('CREATE_DATE', models.DateTimeField(auto_now=True)),
                ('IS_PRIVATE', models.BooleanField(default=False)),
                ('CON_OWNER', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
